CREATE TABLE [stage].[MortgageDeedReferences_NYCOpendata_20161008]
(
[DOCUMENT ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RECORD TYPE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE BY CRFN ] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE BY DOC ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE BY REEL YEAR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE BY REEL BOROUGH] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE BY REEL NBR] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REFERENCE BY REEL PAGE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GOOD THROUGH DATE] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
